services:
  simposio-integracar:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - sqlite_data:/code/data
      - media_data:/code/src/media
      - staticfiles_data:/code/src/staticfiles
    networks:
      - app-network
      - proxy

networks:
  app-network:
    driver: bridge

  proxy:
    external: true

volumes:
  sqlite_data:
  media_data:
  staticfiles_data:
