# Generated by Django 6.0.5 on 2026-05-21 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_user_reviewers_eixotematico_event_and_more'),
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coauthor',
            options={'ordering': ('authorship_order',), 'verbose_name': 'coautor', 'verbose_name_plural': 'coautores'},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name': 'trabalho', 'verbose_name_plural': 'trabalhos'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'submissão', 'verbose_name_plural': 'submissões'},
        ),
        migrations.AddField(
            model_name='paper',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='events.event'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='coauthor',
            unique_together={('paper', 'email'), ('paper', 'user')},
        ),
    ]
