# Generated by Django 6.0.5 on 2026-05-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_coauthor_options_alter_paper_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
    ]
