# Generated by Codex on 2026-05-25

import django.db.models.deletion
from django.db import migrations, models


def assign_first_event_axis(apps, schema_editor):
    Paper = apps.get_model('papers', 'Paper')
    EixoTematico = apps.get_model('events', 'EixoTematico')

    event_axis_by_id = {}
    for eixo in EixoTematico.objects.order_by('event_id', 'pk'):
        event_axis_by_id.setdefault(eixo.event_id, eixo.pk)

    missing_event_ids = sorted(
        set(
            Paper.objects.filter(
                eixo_tematico__isnull=True,
            )
            .exclude(event_id__in=event_axis_by_id)
            .values_list('event_id', flat=True)
        )
    )
    for event_id in missing_event_ids:
        eixo = EixoTematico.objects.create(
            event_id=event_id,
            name='Eixo geral',
        )
        event_axis_by_id[event_id] = eixo.pk

    papers = Paper.objects.filter(eixo_tematico__isnull=True)
    for paper in papers.iterator():
        paper.eixo_tematico_id = event_axis_by_id[paper.event_id]
        paper.save(update_fields=['eixo_tematico'])


def unassign_event_axis(apps, schema_editor):
    Paper = apps.get_model('papers', 'Paper')
    Paper.objects.update(eixo_tematico=None)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_user_reviewers_eixotematico_event_and_more'),
        ('papers', '0003_remove_paper_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='eixo_tematico',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='papers',
                to='events.eixotematico',
                verbose_name='eixo temático',
            ),
        ),
        migrations.RunPython(assign_first_event_axis, unassign_event_axis),
        migrations.AlterField(
            model_name='paper',
            name='eixo_tematico',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='papers',
                to='events.eixotematico',
                verbose_name='eixo temático',
            ),
        ),
    ]
