# Generated by Django 6.0.5 on 2026-05-25 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_user_reviewers_eixotematico_event_and_more'),
        ('papers', '0004_paper_eixo_tematico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coauthor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='coauthor',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='coauthor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coauthored', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(verbose_name='resumo'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='events.event', verbose_name='evento'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
    ]
