# Generated by Django 6.0.5 on 2026-06-15 17:15

from django.db import migrations, models


def number_existing_submissions(apps, schema_editor):
    Submission = apps.get_model('papers', 'Submission')
    paper_ids = Submission.objects.values_list('paper_id', flat=True).distinct()
    for paper_id in paper_ids:
        submissions = Submission.objects.filter(paper_id=paper_id).order_by(
            'created_at',
            'id',
        )
        for version, submission in enumerate(submissions, start=1):
            submission.version = version
            submission.save(update_fields=('version',))


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_alter_coauthor_email_alter_coauthor_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('version',), 'verbose_name': 'submissão', 'verbose_name_plural': 'submissões'},
        ),
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Submetido'), ('under_review', 'Em avaliação'), ('approved', 'Aprovado'), ('approved_with_changes', 'Aprovado com correções'), ('rejected', 'Reprovado'), ('correction_submitted', 'Correção enviada'), ('review_completed', 'Avaliação finalizada')], default='draft', max_length=30, verbose_name='situação'),
        ),
        migrations.AddField(
            model_name='submission',
            name='version',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='versão'),
        ),
        migrations.RunPython(
            number_existing_submissions,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('paper', 'version'), name='unique_submission_version_per_paper'),
        ),
    ]
