# Generated by Django 6.0.5 on 2026-06-24 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_alter_coauthor_email_alter_coauthor_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coauthor',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='coauthor',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('paper', 'user'), name='uniq_coauthor_paper_user'),
        ),
        migrations.AddConstraint(
            model_name='coauthor',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('paper', 'email'), name='uniq_coauthor_paper_email'),
        ),
    ]
