# Generated by Django 6.0.5 on 2026-05-20 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome do evento')),
                ('edition', models.CharField(max_length=50, verbose_name='edicao')),
                ('year', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('organizing_institution', models.CharField(max_length=255, verbose_name='instituicao organizadora')),
                ('submission_period_start', models.DateTimeField(verbose_name='periodo de submissao (inicio)')),
                ('submission_period_end', models.DateTimeField(verbose_name='periodo de submissao (fim)')),
                ('evaluation_period_start', models.DateTimeField(verbose_name='periodo de avaliacao (inicio)')),
                ('evaluation_period_end', models.DateTimeField(verbose_name='periodo de avaliacao (fim)')),
                ('results_publication_date', models.DateTimeField(verbose_name='data de divulgacao dos resultados')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='e-mail de contato da organizacao')),
                ('submission_rules', models.TextField(blank=True, verbose_name='regras gerais de submissao')),
                ('blind_review', models.BooleanField(default=False, help_text='Se ativado, os avaliadores não terão acesso às informações dos autores durante a avaliação.', verbose_name='revisao cega')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-year', 'name', 'edition'],
            },
        ),
    ]
