# Generated by Django 6.0.5 on 2026-05-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EixoTematico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome do eixo temático')),
            ],
            options={
                'verbose_name': 'eixo temático',
                'verbose_name_plural': 'eixos temáticos',
            },
        ),
    ]
