# Generated by Django 6.0.5 on 2026-05-21 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eixotematico'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_reviewers',
            field=models.ManyToManyField(blank=True, help_text='Usuários que atuarão como avaliadores para este evento. Eles terão acesso às submissões durante o período de avaliação.', related_name='events_as_reviewer', through='reviews.Reviewer', to=settings.AUTH_USER_MODEL, verbose_name='avaliadores'),
        ),
        migrations.AddField(
            model_name='eixotematico',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eixos_tematicos', to='events.event', verbose_name='evento'),
        ),
        migrations.AlterUniqueTogether(
            name='eixotematico',
            unique_together={('name', 'event')},
        ),
    ]
