# Generated by Django 6.0.5 on 2026-06-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_user_reviewers_eixotematico_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='minimum_reviewers',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='quantidade mínima de avaliadores'),
        ),
        migrations.AlterField(
            model_name='event',
            name='blind_review',
            field=models.BooleanField(default=False, help_text='Se ativado, avaliadores não verão os autores e autores não verão a identidade dos avaliadores.', verbose_name='revisão duplo-cega'),
        ),
    ]
