# Generated by Django 6.0.5 on 2026-05-21 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_eixotematico'),
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='data de atribuição')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='data de conclusão')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='papers.paper', verbose_name='trabalho')),
            ],
            options={
                'verbose_name': 'atribuição de avaliador',
                'verbose_name_plural': 'atribuições de avaliador',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='nota')),
                ('comments_to_author', models.TextField(verbose_name='comentários ao autor')),
                ('internal_comments', models.TextField(blank=True, verbose_name='comentários internos')),
                ('recommendation', models.CharField(choices=[('accept', 'Aceitar'), ('accept_with_changes', 'Aceitar com correções'), ('reject', 'Rejeitar')], max_length=30, verbose_name='recomendação')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='data do parecer')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.reviewassignment', verbose_name='atribuição')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eixos_tematicos', models.ManyToManyField(blank=True, related_name='reviewers', to='events.eixotematico', verbose_name='eixos temáticos')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='events.event', verbose_name='evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='avaliador')),
            ],
            options={
                'verbose_name': 'avaliador do evento',
                'verbose_name_plural': 'avaliadores do evento',
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reviews.reviewer', verbose_name='avaliador'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewassignment',
            unique_together={('reviewer', 'paper')},
        ),
    ]
