# Generated by Django 6.0.5 on 2026-06-15 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_minimum_reviewers_alter_event_blind_review'),
        ('papers', '0006_alter_submission_options_paper_status_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False, verbose_name='gestor')),
                ('is_decider', models.BooleanField(default=False, verbose_name='decisor')),
            ],
            options={
                'verbose_name': 'membro da comissão',
                'verbose_name_plural': 'membros da comissão',
            },
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='nota')),
            ],
            options={
                'verbose_name': 'nota de critério',
                'verbose_name_plural': 'notas de critérios',
            },
        ),
        migrations.CreateModel(
            name='FinalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('approved', 'Aprovado'), ('approved_with_changes', 'Aprovado com correções'), ('rejected', 'Reprovado')], max_length=30, verbose_name='resultado')),
                ('justification', models.TextField(verbose_name='justificativa')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='publicada em')),
            ],
            options={
                'verbose_name': 'decisão final',
                'verbose_name_plural': 'decisões finais',
            },
        ),
        migrations.CreateModel(
            name='ReviewCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='peso percentual')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'critério de avaliação',
                'verbose_name_plural': 'critérios de avaliação',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReviewInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='versão')),
                ('name', models.CharField(default='Avaliação', max_length=255, verbose_name='nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'instrumento de avaliação',
                'verbose_name_plural': 'instrumentos de avaliação',
                'ordering': ('event', '-version'),
            },
        ),
        migrations.CreateModel(
            name='ReviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='número da rodada')),
                ('starts_at', models.DateTimeField(verbose_name='início')),
                ('ends_at', models.DateTimeField(verbose_name='fim')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('open', 'Aberta'), ('closed', 'Encerrada'), ('decided', 'Decidida')], default='draft', max_length=20, verbose_name='situação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'rodada de avaliação',
                'verbose_name_plural': 'rodadas de avaliação',
                'ordering': ('paper', 'number'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='reviewassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reviewer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='weighted_score',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=4, null=True, verbose_name='média ponderada'),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_review_assignments', to='papers.paper', verbose_name='trabalho legado'),
        ),
        migrations.AddConstraint(
            model_name='reviewer',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_reviewer_per_event'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='events.event', verbose_name='evento'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='criterionscore',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='reviews.review', verbose_name='avaliação'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='decided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to=settings.AUTH_USER_MODEL, verbose_name='decidido por'),
        ),
        migrations.AddField(
            model_name='criterionscore',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='reviews.reviewcriterion', verbose_name='critério'),
        ),
        migrations.AddField(
            model_name='reviewinstrument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_review_instruments', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='reviewinstrument',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_instruments', to='events.event', verbose_name='evento'),
        ),
        migrations.AddField(
            model_name='reviewcriterion',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='reviews.reviewinstrument', verbose_name='instrumento'),
        ),
        migrations.AddField(
            model_name='reviewround',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_review_rounds', to=settings.AUTH_USER_MODEL, verbose_name='criada por'),
        ),
        migrations.AddField(
            model_name='reviewround',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='reviews.reviewinstrument', verbose_name='instrumento'),
        ),
        migrations.AddField(
            model_name='reviewround',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_rounds', to='papers.paper', verbose_name='trabalho'),
        ),
        migrations.AddField(
            model_name='reviewround',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review_round', to='papers.submission', verbose_name='versão avaliada'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='round',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='reviews.reviewround', verbose_name='rodada'),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reviews.reviewround', verbose_name='rodada'),
        ),
        migrations.AddConstraint(
            model_name='reviewassignment',
            constraint=models.UniqueConstraint(fields=('reviewer', 'round'), name='unique_reviewer_assignment_per_round'),
        ),
        migrations.AddConstraint(
            model_name='committeemember',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_committee_member_per_event'),
        ),
        migrations.AddConstraint(
            model_name='criterionscore',
            constraint=models.UniqueConstraint(fields=('review', 'criterion'), name='unique_score_per_review_criterion'),
        ),
        migrations.AddConstraint(
            model_name='criterionscore',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 10)), name='criterion_score_between_zero_and_10'),
        ),
        migrations.AddConstraint(
            model_name='reviewinstrument',
            constraint=models.UniqueConstraint(fields=('event', 'version'), name='unique_review_instrument_version'),
        ),
        migrations.AddConstraint(
            model_name='reviewcriterion',
            constraint=models.UniqueConstraint(fields=('instrument', 'order'), name='unique_criterion_order_per_instrument'),
        ),
        migrations.AddConstraint(
            model_name='reviewcriterion',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0), ('weight__lte', 100)), name='criterion_weight_between_zero_and_100'),
        ),
        migrations.AddConstraint(
            model_name='reviewround',
            constraint=models.UniqueConstraint(fields=('paper', 'number'), name='unique_review_round_number_per_paper'),
        ),
    ]
