# Generated by Django 6.0.5 on 2026-06-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_committeemember_criterionscore_finaldecision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='nota legada'),
        ),
    ]
