# Generated by Codex on 2026-06-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def discard_legacy_review_flow(apps, schema_editor):
    Review = apps.get_model('reviews', 'Review')
    ReviewAssignment = apps.get_model('reviews', 'ReviewAssignment')
    FinalDecision = apps.get_model('reviews', 'FinalDecision')
    Review.objects.all().delete()
    ReviewAssignment.objects.all().delete()
    FinalDecision.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0008_mark_existing_papers_submitted'),
        ('reviews', '0003_alter_review_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            discard_legacy_review_flow,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='reviewassignment',
            name='unique_reviewer_assignment_per_round',
        ),
        migrations.RemoveConstraint(
            model_name='criterionscore',
            name='unique_score_per_review_criterion',
        ),
        migrations.RemoveConstraint(
            model_name='criterionscore',
            name='criterion_score_between_zero_and_10',
        ),
        migrations.RemoveConstraint(
            model_name='reviewinstrument',
            name='unique_review_instrument_version',
        ),
        migrations.RemoveConstraint(
            model_name='reviewcriterion',
            name='unique_criterion_order_per_instrument',
        ),
        migrations.RemoveConstraint(
            model_name='reviewcriterion',
            name='criterion_weight_between_zero_and_100',
        ),
        migrations.RemoveConstraint(
            model_name='reviewround',
            name='unique_review_round_number_per_paper',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='round',
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='paper',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='final_decision',
                to='papers.paper',
                verbose_name='trabalho',
            ),
        ),
        migrations.RemoveField(
            model_name='reviewassignment',
            name='round',
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='paper',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='review_assignments',
                to='papers.paper',
                verbose_name='trabalho',
            ),
        ),
        migrations.RemoveField(
            model_name='review',
            name='score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='weighted_score',
        ),
        migrations.AlterField(
            model_name='finaldecision',
            name='paper',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='final_decision',
                to='papers.paper',
                verbose_name='trabalho',
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='recommendation',
            field=models.CharField(
                choices=[
                    ('approve', 'Aprovar'),
                    ('approve_with_changes', 'Aprovar com alteracoes'),
                    ('reject', 'Recusar'),
                ],
                max_length=30,
                verbose_name='recomendacao',
            ),
        ),
        migrations.AlterField(
            model_name='finaldecision',
            name='result',
            field=models.CharField(
                choices=[
                    ('approved', 'Aprovado'),
                    ('approved_with_changes', 'Aprovado com alteracoes'),
                    ('rejected', 'Recusado'),
                ],
                max_length=30,
                verbose_name='resultado',
            ),
        ),
        migrations.AddConstraint(
            model_name='reviewassignment',
            constraint=models.UniqueConstraint(
                fields=('reviewer', 'paper'),
                name='unique_reviewer_assignment_per_paper',
            ),
        ),
        migrations.DeleteModel(
            name='CriterionScore',
        ),
        migrations.DeleteModel(
            name='ReviewCriterion',
        ),
        migrations.DeleteModel(
            name='ReviewRound',
        ),
        migrations.DeleteModel(
            name='ReviewInstrument',
        ),
        migrations.AlterModelOptions(
            name='committeemember',
            options={
                'verbose_name': 'membro da comissao',
                'verbose_name_plural': 'membros da comissao',
            },
        ),
        migrations.AlterModelOptions(
            name='finaldecision',
            options={
                'verbose_name': 'decisao final',
                'verbose_name_plural': 'decisoes finais',
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={
                'verbose_name': 'avaliacao',
                'verbose_name_plural': 'avaliacoes',
            },
        ),
        migrations.AlterModelOptions(
            name='reviewassignment',
            options={
                'verbose_name': 'atribuicao de avaliador',
                'verbose_name_plural': 'atribuicoes de avaliador',
            },
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='committee_memberships',
                to=settings.AUTH_USER_MODEL,
                verbose_name='usuario',
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='assignment',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='review',
                to='reviews.reviewassignment',
                verbose_name='atribuicao',
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments_to_author',
            field=models.TextField(verbose_name='comentarios ao autor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='internal_comments',
            field=models.TextField(
                blank=True,
                verbose_name='comentarios internos',
            ),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='assigned_at',
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name='data de atribuicao',
            ),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='completed_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='data de conclusao',
            ),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='eixos_tematicos',
            field=models.ManyToManyField(
                blank=True,
                related_name='reviewers',
                to='events.eixotematico',
                verbose_name='eixos tematicos',
            ),
        ),
    ]
