# Generated by Django 6.0.5 on 2026-05-19 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='nome',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=100, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mail'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='cpf')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='telefone')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='instituicao de vinculo')),
                ('affiliation_type', models.CharField(blank=True, choices=[('student', 'Estudante'), ('teacher', 'Professor'), ('technician', 'Tecnico'), ('external_researcher', 'Pesquisador externo'), ('other', 'Outro')], max_length=30, verbose_name='tipo de vinculo')),
                ('education_level', models.CharField(blank=True, max_length=100, verbose_name='nivel de formacao')),
                ('academic_title', models.CharField(blank=True, max_length=100, verbose_name='titulacao')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('lattes_url', models.URLField(blank=True, verbose_name='link do lattes')),
                ('areas_of_activity', models.TextField(blank=True, verbose_name='areas de atuacao')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
    ]
